# Generated by Django 5.2.1 on 2025-05-13 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0002_country_province_company_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Counter.country'),
        ),
    ]
