# Generated by Django 5.2.1 on 2025-05-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0003_alter_province_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='noname', max_length=255),
            preserve_default=False,
        ),
    ]
