# Generated by Django 5.2.1 on 2025-05-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0004_report_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
