# Generated by Django 5.2.1 on 2025-05-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0005_remove_province_country_delete_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalcount',
            name='company',
        ),
        migrations.RemoveField(
            model_name='totalcount',
            name='year',
        ),
    ]
