# Generated by Django 5.2.1 on 2025-05-21 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0006_remove_totalcount_company_remove_totalcount_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalcount',
            name='report',
        ),
        migrations.AddField(
            model_name='totalcount',
            name='year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TotalCountReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counter.report')),
            ],
            options={
                'unique_together': {('report', 'word')},
            },
        ),
    ]
