# Generated by Django 5.2.1 on 2025-05-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0007_remove_totalcount_report_totalcount_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
