# Generated by Django 5.2.1 on 2025-05-26 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0009_alter_report_name_alter_report_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.ForeignKey(blank=True, default='Sin empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='Counter.company'),
        ),
    ]
