# Generated by Django 5.2.1 on 2025-05-26 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0010_alter_report_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counter.company'),
        ),
    ]
