# Generated by Django 5.2.1 on 2025-05-29 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0013_totalcountreport_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalcountreport',
            name='company',
        ),
        migrations.AddField(
            model_name='totalcount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Counter.company'),
        ),
    ]
