# Generated by Django 5.2.1 on 2025-05-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0014_remove_totalcountreport_company_totalcount_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='totalcount',
            unique_together={('year', 'word', 'company')},
        ),
    ]
