# Generated by Django 5.2.1 on 2025-05-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0015_alter_totalcount_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
